### ISSUE TITLE
[BUG] Не работает дверь в казну

### ISSUE THREAD

**Issue by hamurlik** [Moth-gang/Goonwood#43]
## Describe the bug

Дверь в казну вечно заперта, не открывается с помощью "vault key"
Её название почему то "wall" хотя дверь это не стена.

## Round ID:
Gem752-19.32.16

## Steps to Reproduce:
Попытаться открыть дверь в казну ключом "vault key"

## Additional context

![image](https://github.com/user-attachments/assets/edd43d8d-999c-4e70-a9db-c07653bfb76e)

**Comment by Evie7056** [comment]
Не баг. Это секретная дверь открывается паролем, что выставляет монарх/десница/казначей
